(define (domain agenteSeguranca)
    (:requirements :strips)
    (:predicates  (Janela ?jan) 
                  (Porta ?porta) 
                  (Aberta ?porta)
                  (Luz ?luz) 
                  (Ligada ?luz)
                  (Sala ?sala)
                  (Pertence ?obj ?sala)
                  (Corredor ?corr)
                  (LocalSeguranca ?loc)
    )
    
    (:action abrir  :parameters (?loc ?sala ?porta)
                    :precondition (and (LocalSeguranca ?loc) (Corredor ?loc) (Sala ?sala) (Pertence ?porta ?sala) (not (Aberta ?porta)))
                    :effect (Aberta ?porta)
    )
    
)
