(define (domain agenteSeguranca)
    (:requirements :strips)
    (:predicates  (Janela ?obj) 
                  (Porta ?obj) 
                  (Aberta ?obj)
                  (Luz ?obj) 
                  (Ligada ?obj)
                  (Sala ?obj)
                  (Pertence ?obj ?obj)
                  (Corredor ?obj)
                  (LocalSeguranca ?obj)
    )
    
    (:action abrir  :parameters (?loc ?porta)
                    :precondition (and (LocalSeguranca ?loc) (Corredor ?loc))
                    :effect (Aberta ?porta)
    )
    
)
