(define (problem problema2)
    (:domain agenteSeguranca)
    (:objects C1 S1 S2 P1 P2 L1 J1)
    (:init (Corredor C1)
           (Sala S1)
           (Porta P1)
           (not (Aberta P1))
           (Pertence P1 S1)
           (Sala S2)
           (Porta P2)
           (Aberta P2)
           (Pertence P2 S2)
           (Luz L1)
           (not (Ligada L1))
           (Pertence L1 S1)
           (Janela J1)
           (Aberta J1)
           (Pertence J1 S1)
           (LocalSeguranca C1)
    )
    (:goal  (and (not (Ligada L1)) (not (Aberta J1)) (Aberta P2) (LocalSeguranca C1))) ; Objetivo.
)
